version: '3.9'

services:
  # karma-app-gateway
  gateway-backend:
    build: ./karma-app-gateway
    image: msik/karma-app-gateway
    env_file:
      - .env
    networks:
      - karma-app-gateway-net
      - karma-app-net
    ports:
      - 8080:8080
    depends_on:
      - gateway-redis
      - posts-backend
      - users-backend
  gateway-redis:
    image: redis:latest
    hostname: ${KARMA_APP_GATEWAY_REDIS_HOSTNAME}
    networks:
      - karma-app-gateway-net
    volumes:
      - gateway-redis-data:/data
      - ./karma-app-gateway/redis.conf:/usr/local/etc/redis/redis.conf

  # karma-app-posts
  posts-backend:
    build: ./karma-app-posts
    image: msik/karma-app-posts
    hostname: ${KARMA_APP_POSTS_HOST}
    networks:
      - karma-app-posts-net
      - karma-app-net
    env_file:
      - .env
    depends_on:
      posts-mongo:
        condition: service_healthy
  posts-mongo:
    image: mongo:latest
    hostname: ${KARMA_APP_POSTS_DB_HOST}
    networks:
      - karma-app-posts-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${KARMA_APP_POSTS_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${KARMA_APP_POSTS_DB_PASSWORD}
      - MONGO_INITDB_ROOT_DATABASE=${KARMA_APP_POSTS_DB_NAME}
    volumes:
      - posts-db-data:/data/db
      - posts-db-config:/data/configdb
      - ./keyfile:/opt/keyfile/
    healthcheck: # 94 is an error code returned when rs is not initiated.
      test: test "$$(mongosh -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet --eval "try {rs.status().ok} catch(e) {if (e.code == 94) {rs.initiate().ok} else {0} }")" -eq 1
      interval: 10s
      start_period: 30s
    command: mongod --replSet rs0 --keyFile /opt/keyfile

  # karma-app-users
  users-backend:
    build: ./karma-app-users
    image: msik/karma-app-users
    hostname: ${KARMA_APP_USERS_HOST}
    networks:
      - karma-app-users-net
      - karma-app-net
    env_file:
      - .env
    depends_on:
      - users-mongo
  users-mongo:
    image: mongo:latest
    hostname: ${KARMA_APP_USERS_DB_HOST}
    networks:
      - karma-app-users-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${KARMA_APP_USERS_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${KARMA_APP_USERS_DB_PASSWORD}
      - MONGO_INITDB_ROOT_DATABASE=${KARMA_APP_USERS_DB_NAME}
    volumes:
      - users-db-data:/data/db
      - users-db-config:/data/configdb

volumes:
  # karma-app-posts
  posts-db-data:
    driver: local
  posts-db-config:
    driver: local

  # karma-app-users
  users-db-data:
    driver: local
  users-db-config:
    driver: local

  # karma-app-gateway
  gateway-redis-data:
    driver: local

networks:
  # Internal web
  karma-app-gateway-net:
    name: karma-app-gateway-net
    driver: bridge

  # Internal web
  karma-app-posts-net:
    name: karma-app-posts-net
    driver: bridge

  # Internal web
  karma-app-users-net:
    name: karma-app-users-net
    driver: bridge

  # Backends connecting web
  karma-app-net:
    name: karma-app-net
    driver: bridge